### ISSUE TITLE
Add solution and project file for use with Visual Studio

### ISSUE THREAD

**Issue by JimiC** [fuzzysteve/SDE-loaders#1]
As I'm using Visual Studio as the IDE of choice, and as it supports Python apps development, I suggest to add a solution and project file for those using Visual Studio.

**Comment by JimiC** [comment]
Should I provide a PR for this?

**Comment by fuzzysteve** [comment]
If you've got them, sure :)

I just use notepad++, so I don't need it ;)

**Comment by JimiC** [comment]
The PR will contain also a file structure rearrangement according to the latest standards. You can review it and if you don't like it you can deny it.
On another note I strongly suggest the use of [Visual Studio Code](https://code.visualstudio.com/) instead of Notepad++ (personally I uninstalled it along with SublimeText2 in favor of Code).
