### ISSUE TITLE
SQLite basePrice in invTypes table gives wrong type

### ISSUE THREAD

**Issue by mmuszynski** [fuzzysteve/SDE-loaders#10]
SQLite is super finicky about what values are actually in the table since tables use Type Affinity.

The following query on your SQLite version of the data:
`SELECT typeof(basePrice) FROM invTypes WHERE typeID = 16673;`
returns
`integer`
which is unexpected. I suspect that the script is writing these as integer values rather than numeric, which SQLite is expecting, but I will do some research on your script.

**Comment by fuzzysteve** [comment]
This is the older version of my conversion script. I'd suggest looking at https://github.com/fuzzysteve/yamlloader for a better one.
