### ISSUE TITLE
Usage of connection string from config to connect to a DB

### ISSUE THREAD

**Issue by JimiC** [fuzzysteve/SDE-loaders#2]
As the creation of dsn is quite tricky (spend a couple of hours to figure it out), it's preferable to use a config file which will be used to specify the connection string to the DB (`engine_from_config` instead `create_engine`). This way the app could be told to which DB to connect to (mssql, mysql, etc).

**Comment by fuzzysteve** [comment]
I went down a different path. create_engine just takes a connection string. That's now loaded from a config file (for all of them) 

So it's also now pretty simple to push things over to mysql rather than mssql (or should be)
