### ISSUE TITLE
Add ability to drop and recreate the tables

### ISSUE THREAD

**Issue by JimiC** [fuzzysteve/SDE-loaders#4]
It would be wise to add an ability to drop and recreate the tables whenever the app is executed.

**Comment by fuzzysteve** [comment]
The downside is, I'm inserting into the trnTranslations table, and don't want to drop that one, as it has other data in it. And it makes the 'just run again' option not really work (unless I try catch all the inserts on that. Or shift them to upserts)

**Comment by JimiC** [comment]
This brings us to another suggestion. Implementing a sequential importation process. This way the first call to create 'trnTranslations ' will drop and recreate and all other will ignore it.

**Comment by fuzzysteve** [comment]
trnTranslations is the official table from CCP. It comes with some data already in it.

**Comment by JimiC** [comment]
Ah. That's why you haven't stumbled into the PK issue for the languageID. I was running the importation without first restoring the SDE dump. Never the less in that case we can add a 'table exist' check and act accordingly. I have a similar process in my tool for the invTypes table to have backwards compatibility with previous SDE (prior to Aegis).

**Comment by fuzzysteve** [comment]
Still thinking about a suitable way to handle this. The prexisting translations table, which is used by multiple scripts, makes this harder.

**Comment by JimiC** [comment]
As I added support of translations in my tools it turned out that translation tables can be excluded. All other could benefit from a generic way to drop and recreate the tables. I could provide the code logic as I have done it in my tool.
