### ISSUE TITLE
Implement a sequential importation process

### ISSUE THREAD

**Issue by JimiC** [fuzzysteve/SDE-loaders#5]
Implementing a sequential importation process will eliminate the need to execute each importation separately and give better control on dropping and recreating the tables.

**Comment by fuzzysteve** [comment]
Other than the translation tables, they're not interrelated, so they can be run in any order.

If I had to write a wrapper for it, it'd probably just be a command script, running each in turn.

**Comment by JimiC** [comment]
I beat there is a way to call a py from inside another py and just execute one command.

**Comment by fuzzysteve** [comment]
There's import, but I'd need to rework things a little to allow for appropriate calls. (with a ___main___ to when you use it by itself.)

**Comment by JimiC** [comment]
Yeap, usage of ***main*** is the way to go.
