### ISSUE TITLE
Add missing entries in trnTranslationColumns

### ISSUE THREAD

**Issue by JimiC** [fuzzysteve/SDE-loaders#8]
| tcGroupID | tcID | tableName | columnName | masterID |
| :-- | :-- | :-- | :-- | :-- |
| 4 | 6 | dbo.invCategories | categoryName | categoryID |
5 | 7 | dbo.invGroups | groupName | groupID |
5 | 8 | dbo.invTypes | typeName | typeID |
5 | 33 | dbo.invTypes | description | typeID |

**Comment by fuzzysteve** [comment]
setupTranslations.py added
